const imagenes = {
	termas1: require("./Termas/termas1.webp"),
	termas2: require("./Termas/termas2.webp"),
	termas3: require("./Termas/termas3.webp"),
	termas4: require("./Termas/termas4.webp"),
	termas5: require("./Termas/termas5.webp"),
	termas6: require("./Termas/termas6.webp"),
	termas7: require("./Termas/termas7.webp"),
	termas8: require("./Termas/termas8.webp"),
	termas9: require("./Termas/termas9.webp"),
	santaAna1: require("./Santa-Ana/santa-ana1.webp"),
	santaAna2: require("./Santa-Ana/santa-ana2.webp"),
	santaAna3: require("./Santa-Ana/santa-ana3.webp"),
	santaAna4: require("./Santa-Ana/santa-ana4.webp"),
	santaAna5: require("./Santa-Ana/santa-ana5.webp"),
	santaAna6: require("./Santa-Ana/santa-ana6.webp"),
	santaAna7: require("./Santa-Ana/santa-ana7.webp"),
	logo: require("./Hotel-Rio.webp"),
	logojpg: require("./riohotel.jpg"),
	riohetel2: require("./Hotel-Rio2.png"),
	riohetel1: require("./riohotel1.jpg"),
	clasica1: require("./Habitaciones/Clasica/clasica1.webp"),
	clasica2: require("./Habitaciones/Clasica/clasica2.webp"),
	familiar1: require("./Habitaciones/Familiar/familiar1.webp"),
	familiar2: require("./Habitaciones/Familiar/familiar2.webp"),
	familiar3: require("./Habitaciones/Familiar/familiar3.webp"),
	familiar4: require("./Habitaciones/Familiar/familair4.webp"),
	premium1: require("./Habitaciones/Premium/premium1.webp"),
	premium2: require("./Habitaciones/Premium/premium2.webp"),
	suit1: require("./Habitaciones/Suit/sui1.jpg"),
	suit2: require("./Habitaciones/Suit/suit2.webp"),
	suit3: require("./Habitaciones/Suit/sui3.webp"),
	superior1: require("./Habitaciones/Superior/superior1.webp"),
	superior2: require("./Habitaciones/Superior/superiro2.webp"),
	superior3: require("./Habitaciones/Superior/superior3.webp"),
	parroquia: require("./OtrosDestinos/parroquia.jpg"),
	campingChajari: require("./OtrosDestinos/campingchajari1.webp"),
	campingChajari2: require("./OtrosDestinos/campingchajari.webp"),
	museo1: require("./OtrosDestinos/museo1.jpg"),
	museo2: require("./OtrosDestinos/museo2.webp"),

};
export default imagenes;
